classdef MYOutputOBJEmphysemaDensity < PTKPlugin
    % MYOutputOBJEmphysemaDensity. Plugin for outputing the obj emphysema density
    %
    %     This is a plugin for a self-built function of the Pulmonary Toolkit. Plugins can be run using
    %     the gui, or through the interfaces provided by the Pulmonary Toolkit.
    %     See PTKPlugin.m for more information on how to run plugins.
    %
    %     Plugins should not be run directly from your code.
    %
    %     The output image generated by GenerateImageFromResults creates a
    %     colour-coded segmentation image with true airway points shown as blue
    %     and explosion points shown in red.
    %
    %
    %     Licence
    %     -------
    %     Part of the TD Pulmonary Toolkit. https://github.com/tomdoel/pulmonarytoolkit
    %     Author: Tom Doel, 2012.  www.tomdoel.com
    %     Distributed under the GNU GPL v3 licence. Please see website for details.
    %
    
    properties
        ButtonText = 'Output OBJ Emphysema Density'
        ToolTip = 'Output Emphysema data cloud with density information and convert it into exdata and ipdata'
        Category = 'Export'
        
        AllowResultsToBeCached = true
        AlwaysRunPlugin = false
        PluginType = 'ReplaceOverlay'
        HidePluginInDisplay = false
        FlattenPreviewImage = true
        PTKVersion = '1'
        ButtonWidth = 6
        ButtonHeight = 2
        GeneratePreview = true
        Visibility = 'Developer'
    end
    
    methods (Static)
        function results=RunPlugin(dataset,reporting)
            if nargin < 2
                reporting = PTKReportingDefault;
            end
            
            LungDicomImage = PTKLoadImages(dataset.GetImageInfo);
            Raw = LungDicomImage.RawImage;
            
            lungs=dataset.GetResult('PTKLeftAndRightLungs');
            
            % Get OBJ Emph classified data
            data_info = dataset.GetImageInfo;
            current_data_path = data_info.ImagePath;
            Emph_path = uigetdir(current_data_path, 'Select Directory to Read in OBJ Emphysema Data and Lung Data');
            if Emph_path == 0
                reporting.Error('MYOutputOBJEmphysemaDensity:MYOutputOBJEmphysemaDensity', 'Can not read in emphysema Emph classified data');
            end
            
            OBJ_Emph_mask = fullfile(Emph_path,'Emph.hdr');
            Emph_mask_info = analyze75info(OBJ_Emph_mask);
            Emph_Img = analyze75read(Emph_mask_info);
            
            OBJ_lung_mask = fullfile(Emph_path,'Lung.hdr');
            lung_mask_info = analyze75info(OBJ_lung_mask);
            Lung_Img = analyze75read(lung_mask_info);
            
            Original_Emph_Img = Emph_Img;
            
%             % Sample the data
%             Emph_Img = Emph_Img(1:2:end,1:2:end,:);
%             Lung_Img = Lung_Img(1:2:end,1:2:end,:);
%             Raw = Raw(1:2:end,1:2:end,:);
            
            % Upside down the Img
            Emph_Img1 = Emph_Img;
            for i = 1:size(Emph_Img,3)
                Emph_Img(:,:,i) = Emph_Img1(:,:,(size(Emph_Img,3)-i+1));
            end
            Emph_Img = Emph_Img(end:-1:1,:,:);
            
            Lung_Img1 = Lung_Img;
            for i = 1:size(Lung_Img,3)
                Lung_Img(:,:,i) = Lung_Img1(:,:,(size(Lung_Img,3)-i+1));
            end
            Lung_Img = Lung_Img(end:-1:1,:,:);
            
            Original_Emph_Img1 = Original_Emph_Img;
            for i = 1:size(Original_Emph_Img1,3)
                Original_Emph_Img(:,:,i) = Original_Emph_Img1(:,:,(size(Original_Emph_Img,3)-i+1));
            end
            Original_Emph_Img = Original_Emph_Img(end:-1:1,:,:);
            
            % Separate left and right lung
            OBJ_separate_Lung = zeros(size(Lung_Img));
            left_lung_index = 1:6; right_lung_index = 7:12;
            for m = left_lung_index
                OBJ_separate_Lung(Lung_Img==m) = 2;
            end
            for m = right_lung_index
                OBJ_separate_Lung(Lung_Img==m) = 1;
            end
            
            left_index = find(OBJ_separate_Lung==2);
            right_index = find(OBJ_separate_Lung==1);
            
            offset_value = 0;
            VoxelSize=LungDicomImage.VoxelSize;
            OriginalImageSize=LungDicomImage.OriginalImageSize;
            
            % Get the saving path
            data_info=dataset.GetImageInfo;
            current_data_path=data_info.ImagePath;
            save_root_path = uigetdir(current_data_path, 'Select Directory to Save OBJ Emph density data');
            save_full_path=fullfile(save_root_path,'PTKOBJEmphDensity');
            if ~exist(save_full_path)
                mkdir(save_full_path);
            end
            
            % Calculate the unit voxel volume
            unit_voxel_volume = VoxelSize(1).*VoxelSize(2).*VoxelSize(3);
            
            x_coords_left = []; y_coords_left = []; z_coords_left = [];
            x_coords_right = []; y_coords_right = []; z_coords_right = [];
            density_value_left = [];density_value_right = [];
            Emph_index = find(Emph_Img==1);
            [tf_left, ~] = ismember(Emph_index,left_index);
            Emph_index_left = Emph_index(tf_left);
            HU_value_left = LungDicomImage.GrayscaleToRescaled(Raw(Emph_index_left));
            density_left = double(HU_value_left)/1024+1;
            [tf_right, ~] = ismember(Emph_index,right_index);
            Emph_index_right = Emph_index(tf_right);
            HU_value_right = LungDicomImage.GrayscaleToRescaled(Raw(Emph_index_right));
            density_right = double(HU_value_right)/1024+1;
            [x_left,y_left,z_left] = ind2sub(size(Emph_Img),Emph_index_left);
            [x_right,y_right,z_right] = ind2sub(size(Emph_Img),Emph_index_right);
            x_coords_left = [x_coords_left;x_left]; y_coords_left = [y_coords_left;y_left]; z_coords_left = [z_coords_left;z_left];
            x_coords_right = [x_coords_right;x_right]; y_coords_right = [y_coords_right;y_right]; z_coords_right = [z_coords_right;z_right];
            density_value_left = [density_value_left;density_left]; density_value_right = [density_value_right;density_right];
            x_coords_left1 = y_coords_left.*VoxelSize(2);
            y_coords_left1 = OriginalImageSize(2).*VoxelSize(2)-x_coords_left.*VoxelSize(1);
            y_coords_left1 = OriginalImageSize(2)*VoxelSize(2)-y_coords_left1;
            z_coords_left1 = -z_coords_left.*VoxelSize(3);
            x_coords_right1 = y_coords_right.*VoxelSize(2);
            y_coords_right1 = OriginalImageSize(2).*VoxelSize(2)-x_coords_right.*VoxelSize(1);
            y_coords_right1 = OriginalImageSize(2)*VoxelSize(2)-y_coords_right1;
            z_coords_right1 = -z_coords_right.*VoxelSize(3);
            
            save_data_left = [x_coords_left1,y_coords_left1,z_coords_left1];
            save_data_right = [x_coords_right1,y_coords_right1,z_coords_right1];
            
            save_file_name_ipdata_left = strcat('Emphysema','_density_left.ipdata');
            save_file_name_exdata_left = strcat('Emphysema','_density_left.exdata');
            save_file_name_ipdata_right = strcat('Emphysema','_density_right.ipdata');
            save_file_name_exdata_right = strcat('Emphysema','_density_right.exdata');
            
            group_name_left = strcat('Emphysema','_density_left');
            group_name_right = strcat('Emphysema','_density_right');
            
            mean_density_value_left = mean(density_value_left);
            mean_density_value_right = mean(density_value_right);
            SD_density_value_left = sqrt(sum((density_value_left-mean_density_value_left).^2)./length(density_value_left));
            SD_density_value_right = sqrt(sum((density_value_right-mean_density_value_right).^2)./length(density_value_right));
            volume_left = unit_voxel_volume.*length(density_value_left);
            volume_right = unit_voxel_volume.*length(density_value_right);
            
            MYFieldIpdata(save_file_name_ipdata_left,save_data_left,density_value_left,group_name_left,0,save_full_path);
            MYExportField(save_file_name_exdata_left,save_data_left,density_value_left,group_name_left,offset_value,save_full_path);
            offset_value = offset_value + length(x_coords_left) + 100;
            MYFieldIpdata(save_file_name_ipdata_right,save_data_right,density_value_right,group_name_right,0,save_full_path);
            MYExportField(save_file_name_exdata_right,save_data_right,density_value_right,group_name_right,offset_value,save_full_path);
            offset_value = offset_value + length(x_coords_right) + 100;
            
            [start_crop,end_crop]=MYGetLungROIForCT(LungDicomImage);
            Crop_Emph_Img = Original_Emph_Img(start_crop(1):end_crop(1),start_crop(2):end_crop(2),start_crop(3):end_crop(3));
            Crop_Emph_Img = uint8(Crop_Emph_Img);
            
            mean_density_value_left
            mean_density_value_right
            SD_density_value_left
            SD_density_value_right
            volume_left
            volume_right
            
            lungs.ChangeRawImage(Crop_Emph_Img);
            results = lungs.Copy;
        end
    end
end
