classdef MYViewPASSLung < PTKPlugin
    % MYViewPASSLung. Plugin for viewing each PASS lung segmentation result in PTK viewer
    %
    %     This is a plugin for a self-built function of the Pulmonary Toolkit. Plugins can be run using
    %     the gui, or through the interfaces provided by the Pulmonary Toolkit.
    %     See PTKPlugin.m for more information on how to run plugins.
    %
    %     Plugins should not be run directly from your code.
    %
    %     structure.
    %
    %     The output image generated by GenerateImageFromResults creates a
    %     colour-coded segmentation image with true airway points shown as blue
    %     and explosion points shown in red.
    %
    %
    %     Licence
    %     -------
    %     Part of the TD Pulmonary Toolkit. https://github.com/tomdoel/pulmonarytoolkit
    %     Author: Tom Doel, 2012.  www.tomdoel.com
    %     Distributed under the GNU GPL v3 licence. Please see website for details.
    %
    
    properties
        ButtonText = 'View PASS Lungs'
        ToolTip = 'Shows lung segmentation result of PASS'
        Category = 'Lungs'
        
        AllowResultsToBeCached = true
        AlwaysRunPlugin = false
        PluginType = 'ReplaceOverlay'
        HidePluginInDisplay = false
        FlattenPreviewImage = true
        PTKVersion = '1'
        ButtonWidth = 6
        ButtonHeight = 2
        GeneratePreview = true
        Visibility = 'Developer'
        
        EnableModes = PTKModes.EditMode
        SubMode = PTKSubModes.FixedBoundariesEditing
    end
    
    methods (Static)
        function results = RunPlugin(dataset,reporting)
            if nargin < 2
                reporting = PTKReportingDefault;
            end
            DicomDataset = dataset.GetResult('PTKOriginalImage');%% Get the raw PTKDicom data
            ImageSize = DicomDataset.ImageSize;
            row_num=ImageSize(1);col_num=ImageSize(2);sli_num=ImageSize(3);
            
            % Get PASS Lung segmentation result
            data_info = dataset.GetImageInfo;
            current_data_path = data_info.ImagePath;
            PASS_lung_path = uigetdir(current_data_path, 'Select Directory to Read in PASS Lung Segmentation Result');
            if PASS_lung_path == 0
                reporting.Error('MYViewPASSLung:ProgramErro', 'Can not read in PASS lung segmentation result');
            end
            
            PASS_lung_mask_name = fullfile(PASS_lung_path,'LungSmooth.mask.mask.hdr');
            lung_mask_info = analyze75info(PASS_lung_mask_name);
            lung_mask = analyze75read(lung_mask_info);
            lung_mask1 = lung_mask;
            lung_mask(lung_mask1==5) = 2;
            lung_mask(lung_mask1==17) = 1;
            
            lungs = dataset.GetResult('PTKLeftAndRightLungs');
            results = lungs.Copy;
            [start_crop,end_crop] = MYGetLungROIForCT(DicomDataset);
            raw_lung = lung_mask(start_crop(1):end_crop(1),start_crop(2):end_crop(2),start_crop(3):end_crop(3));
            results.ChangeRawImage(raw_lung);
        end
    end
end
